name: fixtures_web_scraping
description: "A new Flutter project."

version: 1.0.4+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.20.0
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/icons/icon_app.jpg"
  adaptive_icon_foreground: "lib/core/assets/icons/logo__foreground.png"
  adaptive_icon_background: "#181829"
flutter:

  uses-material-design: true
  assets:
    - lib/core/assets/images/splash/
    - lib/core/assets/icons/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: lib/core/assets/fonts/SourceSansPro-Regular.otf
          weight: 400
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-Bold.otf
          weight: 700
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-It.otf
          weight: 400
          style: italic
        - asset: lib/core/assets/fonts/SourceSansPro-BoldIt.otf
          weight: 700
          style: italic
        - asset: lib/core/assets/fonts/SourceSansPro-Black.otf
          weight: 900
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-BlackIt.otf
          weight: 900
          style: italic
        - asset: lib/core/assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 200
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-ExtraLightIt.otf
          weight: 200
          style: italic
        - asset: lib/core/assets/fonts/SourceSansPro-Light.otf
          weight: 300
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-LightIt.otf
          weight: 300
          style: italic
        - asset: lib/core/assets/fonts/SourceSansPro-Semibold.otf
          weight: 600
          style: normal
        - asset: lib/core/assets/fonts/SourceSansPro-SemiboldIt.otf
          weight: 600
          style: italic
#! Splash screen
flutter_native_splash:
  color: "#181829"
  image: lib/core/assets/images/splash/logo.png

  android_12:
    icon_background_color: "#181829"
    image: lib/core/assets/images/splash/logo.png
